"""Canonical Silver Arrow schemas shared across writers and transforms."""

from __future__ import annotations

import pyarrow as pa

# Dataset-specific schemas (per PRD Section 8.7)
SILVER_SCHEMAS = {
    "bars": pa.schema(
        [
            ("event_id", pa.string()),
            ("provider", pa.string()),
            ("feed", pa.string()),
            ("instrument_type", pa.string()),
            ("instrument_key", pa.string()),
            ("symbol", pa.string()),
            ("ts_event", pa.timestamp("us", tz="UTC")),
            ("ts_ingest", pa.timestamp("us", tz="UTC")),
            ("ts_available", pa.timestamp("us", tz="UTC")),
            ("source", pa.string()),
            ("schema_version", pa.string()),
            ("quality_flags", pa.list_(pa.string())),
            # Bars-specific
            ("timeframe", pa.string()),
            ("bar_start_ts", pa.timestamp("us", tz="UTC")),
            ("open", pa.float64()),
            ("high", pa.float64()),
            ("low", pa.float64()),
            ("close", pa.float64()),
            ("volume", pa.float64()),
            ("trade_count", pa.int64()),
            ("vwap", pa.float64()),
        ]
    ),
    "borrow_cost": pa.schema(
        [
            ("event_id", pa.string()),
            ("provider", pa.string()),
            ("feed", pa.string()),
            ("instrument_type", pa.string()),
            ("instrument_key", pa.string()),
            ("symbol", pa.string()),
            ("ts_event", pa.timestamp("us", tz="UTC")),
            ("ts_ingest", pa.timestamp("us", tz="UTC")),
            ("ts_available", pa.timestamp("us", tz="UTC")),
            ("source", pa.string()),
            ("schema_version", pa.string()),
            ("quality_flags", pa.list_(pa.string())),
            # Borrow cost-specific
            ("fee_rate", pa.float64()),
            ("rebate_rate", pa.float64()),
            ("short_shares_available", pa.float64()),
            ("currency", pa.string()),
            ("name", pa.string()),
        ]
    ),
    "quotes": pa.schema(
        [
            ("event_id", pa.string()),
            ("provider", pa.string()),
            ("feed", pa.string()),
            ("instrument_type", pa.string()),
            ("instrument_key", pa.string()),
            ("symbol", pa.string()),
            ("ts_event", pa.timestamp("us", tz="UTC")),
            ("ts_ingest", pa.timestamp("us", tz="UTC")),
            ("ts_available", pa.timestamp("us", tz="UTC")),
            ("source", pa.string()),
            ("schema_version", pa.string()),
            ("quality_flags", pa.list_(pa.string())),
            # Quotes-specific
            ("bid_px", pa.float64()),
            ("bid_sz", pa.float64()),
            ("ask_px", pa.float64()),
            ("ask_sz", pa.float64()),
            ("bid_exchange", pa.string()),
            ("ask_exchange", pa.string()),
            ("conditions", pa.list_(pa.string())),
            ("tape", pa.string()),
        ]
    ),
    "trades": pa.schema(
        [
            ("event_id", pa.string()),
            ("provider", pa.string()),
            ("feed", pa.string()),
            ("instrument_type", pa.string()),
            ("instrument_key", pa.string()),
            ("symbol", pa.string()),
            ("ts_event", pa.timestamp("us", tz="UTC")),
            ("ts_ingest", pa.timestamp("us", tz="UTC")),
            ("ts_available", pa.timestamp("us", tz="UTC")),
            ("source", pa.string()),
            ("schema_version", pa.string()),
            ("quality_flags", pa.list_(pa.string())),
            # Trades-specific
            ("trade_id", pa.string()),
            ("price", pa.float64()),
            ("size", pa.float64()),
            ("exchange", pa.string()),
            ("exchange_type", pa.string()),  # Code table: "sip" (equity), "opra" (option), null (crypto)
            ("tape", pa.string()),
            ("conditions", pa.list_(pa.string())),
            ("condition_type", pa.string()),  # Code table: "sip" (equity), "opra" (option), null (crypto)
            ("taker_side", pa.string()),
            ("update", pa.string()),
        ]
    ),
    "flow_alerts": pa.schema(
        [
            ("event_id", pa.string()),
            ("provider", pa.string()),
            ("feed", pa.string()),
            ("instrument_type", pa.string()),
            ("instrument_key", pa.string()),
            ("symbol", pa.string()),
            ("ts_event", pa.timestamp("us", tz="UTC")),
            ("ts_ingest", pa.timestamp("us", tz="UTC")),
            ("ts_available", pa.timestamp("us", tz="UTC")),
            ("source", pa.string()),
            ("schema_version", pa.string()),
            ("quality_flags", pa.list_(pa.string())),
            # Flow-specific
            ("underlying", pa.string()),
            ("occ_symbol", pa.string()),
            ("expiry", pa.date32()),
            ("strike", pa.float64()),
            ("put_call", pa.string()),
            ("premium", pa.float64()),
            ("volume", pa.float64()),
            ("open_interest", pa.float64()),
            ("spot_px", pa.float64()),
            ("contract_px", pa.float64()),
            ("alert_type", pa.string()),
            ("side", pa.string()),
            ("aggressor", pa.string()),
            # UW additional fields (P1)
            ("is_sweep", pa.bool_()),
            ("is_unusual", pa.bool_()),
            ("trade_count", pa.int64()),
            ("volume_oi_ratio", pa.float64()),
            ("total_ask_side_prem", pa.float64()),
            ("total_bid_side_prem", pa.float64()),
            ("has_floor", pa.bool_()),
            ("has_multileg", pa.bool_()),
            ("has_singleleg", pa.bool_()),
            ("all_opening_trades", pa.bool_()),
            ("total_size", pa.int64()),
            ("expiry_count", pa.int64()),
            ("sentiment", pa.string()),
            # GEX / VEX enrichment from UWPoller
            ("gex", pa.float64()),
            ("vex", pa.float64()),
            ("max_pain_strike", pa.float64()),
            ("max_pain_distance_pct", pa.float64()),
        ]
    ),
    "darkpool": pa.schema(
        [
            ("event_id", pa.string()),
            ("provider", pa.string()),
            ("feed", pa.string()),
            ("instrument_type", pa.string()),
            ("instrument_key", pa.string()),
            ("symbol", pa.string()),
            ("ts_event", pa.timestamp("us", tz="UTC")),
            ("ts_ingest", pa.timestamp("us", tz="UTC")),
            ("ts_available", pa.timestamp("us", tz="UTC")),
            ("source", pa.string()),
            ("schema_version", pa.string()),
            ("quality_flags", pa.list_(pa.string())),
            # Darkpool-specific
            ("underlying", pa.string()),
            ("price", pa.float64()),
            ("size", pa.float64()),
            ("notional", pa.float64()),
            ("venue", pa.string()),
            ("print_id", pa.string()),
            ("nbbo_bid", pa.float64()),
            ("nbbo_ask", pa.float64()),
            ("nbbo_bid_size", pa.float64()),
            ("nbbo_ask_size", pa.float64()),
            ("ext_hours", pa.string()),
            ("sale_cond_codes", pa.string()),
            ("trade_code", pa.string()),
            ("trade_settlement", pa.string()),
            ("canceled", pa.bool_()),
        ]
    ),
    "sector_tide": pa.schema(
        [
            ("event_id", pa.string()),
            ("provider", pa.string()),
            ("feed", pa.string()),
            ("instrument_type", pa.string()),
            ("instrument_key", pa.string()),
            ("symbol", pa.string()),
            ("ts_event", pa.timestamp("us", tz="UTC")),
            ("ts_ingest", pa.timestamp("us", tz="UTC")),
            ("ts_available", pa.timestamp("us", tz="UTC")),
            ("source", pa.string()),
            ("schema_version", pa.string()),
            ("quality_flags", pa.list_(pa.string())),
            # Sector tide-specific
            ("sector", pa.string()),
            ("net_call_premium", pa.float64()),
            ("net_put_premium", pa.float64()),
            ("net_volume", pa.float64()),
            ("sentiment", pa.string()),
            ("call_put_ratio", pa.float64()),
        ]
    ),
    "market_tide": pa.schema(
        [
            ("event_id", pa.string()),
            ("provider", pa.string()),
            ("feed", pa.string()),
            ("instrument_type", pa.string()),
            ("instrument_key", pa.string()),
            ("symbol", pa.string()),
            ("ts_event", pa.timestamp("us", tz="UTC")),
            ("ts_ingest", pa.timestamp("us", tz="UTC")),
            ("ts_available", pa.timestamp("us", tz="UTC")),
            ("source", pa.string()),
            ("schema_version", pa.string()),
            ("quality_flags", pa.list_(pa.string())),
            # Market tide-specific
            ("tide_date", pa.string()),
            ("total_call_premium", pa.float64()),
            ("total_put_premium", pa.float64()),
            ("net_volume", pa.float64()),
            ("sentiment", pa.string()),
            ("call_put_ratio", pa.float64()),
        ]
    ),
    # Phase 1: Core Analytics
    "greek_exposure": pa.schema(
        [
            ("event_id", pa.string()),
            ("provider", pa.string()),
            ("feed", pa.string()),
            ("instrument_type", pa.string()),
            ("instrument_key", pa.string()),
            ("symbol", pa.string()),
            ("ts_event", pa.timestamp("us", tz="UTC")),
            ("ts_ingest", pa.timestamp("us", tz="UTC")),
            ("ts_available", pa.timestamp("us", tz="UTC")),
            ("source", pa.string()),
            ("schema_version", pa.string()),
            ("quality_flags", pa.list_(pa.string())),
            ("call_gamma", pa.float64()),
            ("put_gamma", pa.float64()),
            ("call_delta", pa.float64()),
            ("put_delta", pa.float64()),
            ("call_vanna", pa.float64()),
            ("put_vanna", pa.float64()),
            ("call_charm", pa.float64()),
            ("put_charm", pa.float64()),
            ("strike", pa.float64()),
            ("expiry", pa.date32()),
            ("dte", pa.int64()),
        ]
    ),
    "max_pain": pa.schema(
        [
            ("event_id", pa.string()),
            ("provider", pa.string()),
            ("feed", pa.string()),
            ("instrument_type", pa.string()),
            ("instrument_key", pa.string()),
            ("symbol", pa.string()),
            ("ts_event", pa.timestamp("us", tz="UTC")),
            ("ts_ingest", pa.timestamp("us", tz="UTC")),
            ("ts_available", pa.timestamp("us", tz="UTC")),
            ("source", pa.string()),
            ("schema_version", pa.string()),
            ("quality_flags", pa.list_(pa.string())),
            ("expiry", pa.date32()),
            ("max_pain_strike", pa.float64()),
            ("call_oi", pa.int64()),
            ("put_oi", pa.int64()),
        ]
    ),
    "net_premium_tick": pa.schema(
        [
            ("event_id", pa.string()),
            ("provider", pa.string()),
            ("feed", pa.string()),
            ("instrument_type", pa.string()),
            ("instrument_key", pa.string()),
            ("symbol", pa.string()),
            ("ts_event", pa.timestamp("us", tz="UTC")),
            ("ts_ingest", pa.timestamp("us", tz="UTC")),
            ("ts_available", pa.timestamp("us", tz="UTC")),
            ("source", pa.string()),
            ("schema_version", pa.string()),
            ("quality_flags", pa.list_(pa.string())),
            ("net_call_premium", pa.float64()),
            ("net_put_premium", pa.float64()),
            ("call_volume", pa.float64()),
            ("put_volume", pa.float64()),
            # Additional UW fields
            ("net_delta", pa.float64()),
            ("net_call_volume", pa.float64()),
            ("net_put_volume", pa.float64()),
            ("call_volume_ask_side", pa.float64()),
            ("call_volume_bid_side", pa.float64()),
            ("put_volume_ask_side", pa.float64()),
            ("put_volume_bid_side", pa.float64()),
            ("tape_time", pa.string()),
        ]
    ),
    "hottest_chain": pa.schema(
        [
            ("event_id", pa.string()),
            ("provider", pa.string()),
            ("feed", pa.string()),
            ("instrument_type", pa.string()),
            ("instrument_key", pa.string()),
            ("symbol", pa.string()),
            ("ts_event", pa.timestamp("us", tz="UTC")),
            ("ts_ingest", pa.timestamp("us", tz="UTC")),
            ("ts_available", pa.timestamp("us", tz="UTC")),
            ("source", pa.string()),
            ("schema_version", pa.string()),
            ("quality_flags", pa.list_(pa.string())),
            ("contract_symbol", pa.string()),
            ("underlying", pa.string()),
            ("strike", pa.float64()),
            ("expiry", pa.date32()),
            ("put_call", pa.string()),
            ("volume", pa.float64()),
            ("open_interest", pa.float64()),
            ("premium", pa.float64()),
            ("iv", pa.float64()),
        ]
    ),
    # Phase 2: Reference Data
    "earnings": pa.schema(
        [
            ("event_id", pa.string()),
            ("provider", pa.string()),
            ("feed", pa.string()),
            ("instrument_type", pa.string()),
            ("instrument_key", pa.string()),
            ("symbol", pa.string()),
            ("ts_event", pa.timestamp("us", tz="UTC")),
            ("ts_ingest", pa.timestamp("us", tz="UTC")),
            ("ts_available", pa.timestamp("us", tz="UTC")),
            ("source", pa.string()),
            ("schema_version", pa.string()),
            ("quality_flags", pa.list_(pa.string())),
            ("earnings_date", pa.date32()),
            ("time", pa.string()),
            ("eps_estimate", pa.float64()),
            ("eps_actual", pa.float64()),
            ("revenue_estimate", pa.float64()),
            ("revenue_actual", pa.float64()),
            # Additional UW fields
            ("expected_move", pa.float64()),
            ("expected_move_pct", pa.float64()),
            ("prior_close", pa.float64()),
            ("has_options", pa.bool_()),
            ("market_cap", pa.float64()),
            ("sector", pa.string()),
            # Earnings reaction fields
            ("is_s_p_500", pa.bool_()),
            ("post_earnings_close", pa.float64()),
            ("reaction", pa.float64()),
        ]
    ),
    "corporate_action": pa.schema(
        [
            ("event_id", pa.string()),
            ("provider", pa.string()),
            ("feed", pa.string()),
            ("instrument_type", pa.string()),
            ("instrument_key", pa.string()),
            ("symbol", pa.string()),
            ("ts_event", pa.timestamp("us", tz="UTC")),
            ("ts_ingest", pa.timestamp("us", tz="UTC")),
            ("ts_available", pa.timestamp("us", tz="UTC")),
            ("source", pa.string()),
            ("schema_version", pa.string()),
            ("quality_flags", pa.list_(pa.string())),
            # Corporate action core
            ("id", pa.string()),
            ("action_type", pa.string()),
            # Dates
            ("ex_date", pa.date32()),
            ("record_date", pa.date32()),
            ("payable_date", pa.date32()),
            ("process_date", pa.date32()),
            ("effective_date", pa.date32()),
            ("due_bill_redemption_date", pa.date32()),
            ("expiration_date", pa.date32()),
            # Financial details
            ("amount", pa.float64()),
            ("ratio", pa.string()),
            ("new_rate", pa.float64()),
            ("old_rate", pa.float64()),
            ("cash_rate", pa.float64()),
            # CUSIP identifiers
            ("cusip", pa.string()),
            ("old_cusip", pa.string()),
            ("new_cusip", pa.string()),
            # Merger-specific
            ("acquirer_symbol", pa.string()),
            ("acquirer_cusip", pa.string()),
            ("acquirer_rate", pa.float64()),
            ("acquiree_symbol", pa.string()),
            ("acquiree_cusip", pa.string()),
            ("acquiree_rate", pa.float64()),
            # Spin-off / rights distribution
            ("source_symbol", pa.string()),
            ("source_cusip", pa.string()),
            ("source_rate", pa.float64()),
            ("new_symbol", pa.string()),
            # Unit split alternate security
            ("alternate_symbol", pa.string()),
            ("alternate_cusip", pa.string()),
            ("alternate_rate", pa.float64()),
            # Name change
            ("old_symbol", pa.string()),
            # Dividend flags
            ("special", pa.bool_()),
            ("foreign", pa.bool_()),
        ]
    ),
    # Phase 3: Screeners
    "most_active": pa.schema(
        [
            ("event_id", pa.string()),
            ("provider", pa.string()),
            ("feed", pa.string()),
            ("instrument_type", pa.string()),
            ("instrument_key", pa.string()),
            ("symbol", pa.string()),
            ("ts_event", pa.timestamp("us", tz="UTC")),
            ("ts_ingest", pa.timestamp("us", tz="UTC")),
            ("ts_available", pa.timestamp("us", tz="UTC")),
            ("source", pa.string()),
            ("schema_version", pa.string()),
            ("quality_flags", pa.list_(pa.string())),
            ("volume", pa.float64()),
            ("trade_count", pa.int64()),
            # Additional market data fields
            ("vwap", pa.float64()),
            ("price", pa.float64()),
            ("change", pa.float64()),
            ("change_percent", pa.float64()),
        ]
    ),
    "mover": pa.schema(
        [
            ("event_id", pa.string()),
            ("provider", pa.string()),
            ("feed", pa.string()),
            ("instrument_type", pa.string()),
            ("instrument_key", pa.string()),
            ("symbol", pa.string()),
            ("ts_event", pa.timestamp("us", tz="UTC")),
            ("ts_ingest", pa.timestamp("us", tz="UTC")),
            ("ts_available", pa.timestamp("us", tz="UTC")),
            ("source", pa.string()),
            ("schema_version", pa.string()),
            ("quality_flags", pa.list_(pa.string())),
            ("price", pa.float64()),
            ("change", pa.float64()),
            ("percent_change", pa.float64()),
            ("direction", pa.string()),
            # Additional fields
            ("volume", pa.int64()),
        ]
    ),
    "screener_result": pa.schema(
        [
            ("event_id", pa.string()),
            ("provider", pa.string()),
            ("feed", pa.string()),
            ("instrument_type", pa.string()),
            ("instrument_key", pa.string()),
            ("symbol", pa.string()),
            ("ts_event", pa.timestamp("us", tz="UTC")),
            ("ts_ingest", pa.timestamp("us", tz="UTC")),
            ("ts_available", pa.timestamp("us", tz="UTC")),
            ("source", pa.string()),
            ("schema_version", pa.string()),
            ("quality_flags", pa.list_(pa.string())),
            # Core
            ("price", pa.float64()),
            ("volume", pa.float64()),
            ("market_cap", pa.float64()),
            ("sector", pa.string()),
            ("call_volume", pa.float64()),
            ("put_volume", pa.float64()),
            ("iv_rank", pa.float64()),
            # IV metrics
            ("iv30d", pa.float64()),
            ("iv30d_1d", pa.float64()),
            ("iv30d_1w", pa.float64()),
            ("iv30d_1m", pa.float64()),
            ("volatility", pa.float64()),
            # Flow / premium metrics
            ("bearish_premium", pa.float64()),
            ("bullish_premium", pa.float64()),
            ("call_premium", pa.float64()),
            ("put_premium", pa.float64()),
            ("net_call_premium", pa.float64()),
            ("net_put_premium", pa.float64()),
            # OI data
            ("call_open_interest", pa.float64()),
            ("put_open_interest", pa.float64()),
            ("total_open_interest", pa.float64()),
            ("prev_call_oi", pa.float64()),
            ("prev_put_oi", pa.float64()),
            # Volume breakdowns
            ("call_volume_ask_side", pa.float64()),
            ("call_volume_bid_side", pa.float64()),
            ("put_volume_ask_side", pa.float64()),
            ("put_volume_bid_side", pa.float64()),
            # Average volume metrics
            ("avg_30_day_call_volume", pa.float64()),
            ("avg_30_day_put_volume", pa.float64()),
            ("avg_3_day_call_volume", pa.float64()),
            ("avg_3_day_put_volume", pa.float64()),
            ("avg_7_day_call_volume", pa.float64()),
            ("avg_7_day_put_volume", pa.float64()),
            # Market data
            ("prev_close", pa.float64()),
            ("week_52_high", pa.float64()),
            ("week_52_low", pa.float64()),
            ("relative_volume", pa.float64()),
            ("implied_move", pa.float64()),
            ("implied_move_perc", pa.float64()),
            ("put_call_ratio", pa.float64()),
            # Metadata
            ("is_index", pa.bool_()),
            ("issue_type", pa.string()),
            ("er_time", pa.string()),
            ("next_earnings_date", pa.string()),
            ("next_dividend_date", pa.string()),
            ("full_name", pa.string()),
        ]
    ),
    # Phase 4: Advanced Analytics
    "iv_rank": pa.schema(
        [
            ("event_id", pa.string()),
            ("provider", pa.string()),
            ("feed", pa.string()),
            ("instrument_type", pa.string()),
            ("instrument_key", pa.string()),
            ("symbol", pa.string()),
            ("ts_event", pa.timestamp("us", tz="UTC")),
            ("ts_ingest", pa.timestamp("us", tz="UTC")),
            ("ts_available", pa.timestamp("us", tz="UTC")),
            ("source", pa.string()),
            ("schema_version", pa.string()),
            ("quality_flags", pa.list_(pa.string())),
            ("iv_rank", pa.float64()),
            ("iv_percentile", pa.float64()),
            ("current_iv", pa.float64()),
            ("one_year_high", pa.float64()),
            ("one_year_low", pa.float64()),
            # Additional fields
            ("close", pa.float64()),
            ("date", pa.string()),
        ]
    ),
    "iv_term_structure": pa.schema(
        [
            ("event_id", pa.string()),
            ("provider", pa.string()),
            ("feed", pa.string()),
            ("instrument_type", pa.string()),
            ("instrument_key", pa.string()),
            ("symbol", pa.string()),
            ("ts_event", pa.timestamp("us", tz="UTC")),
            ("ts_ingest", pa.timestamp("us", tz="UTC")),
            ("ts_available", pa.timestamp("us", tz="UTC")),
            ("source", pa.string()),
            ("schema_version", pa.string()),
            ("quality_flags", pa.list_(pa.string())),
            ("expiry", pa.date32()),
            ("iv", pa.float64()),
            ("dte", pa.int64()),
            ("call_iv", pa.float64()),
            ("put_iv", pa.float64()),
        ]
    ),
    "volatility_stats": pa.schema(
        [
            ("event_id", pa.string()),
            ("provider", pa.string()),
            ("feed", pa.string()),
            ("instrument_type", pa.string()),
            ("instrument_key", pa.string()),
            ("symbol", pa.string()),
            ("ts_event", pa.timestamp("us", tz="UTC")),
            ("ts_ingest", pa.timestamp("us", tz="UTC")),
            ("ts_available", pa.timestamp("us", tz="UTC")),
            ("source", pa.string()),
            ("schema_version", pa.string()),
            ("quality_flags", pa.list_(pa.string())),
            ("realized_vol_30d", pa.float64()),
            ("realized_vol_60d", pa.float64()),
            ("realized_vol_90d", pa.float64()),
            ("iv_30d", pa.float64()),
            ("iv_percentile", pa.float64()),
            ("hv_iv_ratio", pa.float64()),
        ]
    ),
    "oi_change": pa.schema(
        [
            ("event_id", pa.string()),
            ("provider", pa.string()),
            ("feed", pa.string()),
            ("instrument_type", pa.string()),
            ("instrument_key", pa.string()),
            ("symbol", pa.string()),
            ("ts_event", pa.timestamp("us", tz="UTC")),
            ("ts_ingest", pa.timestamp("us", tz="UTC")),
            ("ts_available", pa.timestamp("us", tz="UTC")),
            ("source", pa.string()),
            ("schema_version", pa.string()),
            ("quality_flags", pa.list_(pa.string())),
            ("oi_date", pa.date32()),
            ("call_oi", pa.int64()),
            ("put_oi", pa.int64()),
            ("call_oi_change", pa.int64()),
            ("put_oi_change", pa.int64()),
            # Additional UW fields
            ("avg_price", pa.float64()),
            ("prev_oi", pa.float64()),
            ("option_symbol", pa.string()),
            ("volume", pa.float64()),
            ("trades", pa.float64()),
            # Additional UW OI fields
            ("last_ask", pa.float64()),
            ("last_bid", pa.float64()),
            ("last_fill", pa.float64()),
            ("percentage_of_total", pa.float64()),
            ("prev_ask_volume", pa.int64()),
            ("prev_bid_volume", pa.int64()),
            ("prev_multi_leg_volume", pa.int64()),
            ("prev_total_premium", pa.float64()),
            ("last_date", pa.string()),
            ("prev_mid_volume", pa.int64()),
            ("prev_neutral_volume", pa.int64()),
            ("prev_stock_multi_leg_volume", pa.int64()),
        ]
    ),
    "historic_option_volume": pa.schema(
        [
            ("event_id", pa.string()),
            ("provider", pa.string()),
            ("feed", pa.string()),
            ("instrument_type", pa.string()),
            ("instrument_key", pa.string()),
            ("symbol", pa.string()),
            ("ts_event", pa.timestamp("us", tz="UTC")),
            ("ts_ingest", pa.timestamp("us", tz="UTC")),
            ("ts_available", pa.timestamp("us", tz="UTC")),
            ("source", pa.string()),
            ("schema_version", pa.string()),
            ("quality_flags", pa.list_(pa.string())),
            ("hov_date", pa.date32()),
            ("expiry", pa.date32()),
            ("volume", pa.float64()),
            ("open_interest", pa.float64()),
            ("call_volume", pa.float64()),
            ("put_volume", pa.float64()),
            ("premium", pa.float64()),
        ]
    ),
    "etf_holding": pa.schema(
        [
            ("event_id", pa.string()),
            ("provider", pa.string()),
            ("feed", pa.string()),
            ("instrument_type", pa.string()),
            ("instrument_key", pa.string()),
            ("symbol", pa.string()),
            ("ts_event", pa.timestamp("us", tz="UTC")),
            ("ts_ingest", pa.timestamp("us", tz="UTC")),
            ("ts_available", pa.timestamp("us", tz="UTC")),
            ("source", pa.string()),
            ("schema_version", pa.string()),
            ("quality_flags", pa.list_(pa.string())),
            ("etf_symbol", pa.string()),
            ("holding_symbol", pa.string()),
            ("weight", pa.float64()),
            ("shares", pa.int64()),
            ("market_value", pa.float64()),
        ]
    ),
    "etf_flow": pa.schema(
        [
            ("event_id", pa.string()),
            ("provider", pa.string()),
            ("feed", pa.string()),
            ("instrument_type", pa.string()),
            ("instrument_key", pa.string()),
            ("symbol", pa.string()),
            ("ts_event", pa.timestamp("us", tz="UTC")),
            ("ts_ingest", pa.timestamp("us", tz="UTC")),
            ("ts_available", pa.timestamp("us", tz="UTC")),
            ("source", pa.string()),
            ("schema_version", pa.string()),
            ("quality_flags", pa.list_(pa.string())),
            ("flow_date", pa.date32()),
            ("inflow", pa.float64()),
            ("outflow", pa.float64()),
            ("net_flow", pa.float64()),
        ]
    ),
    "short_data": pa.schema(
        [
            ("event_id", pa.string()),
            ("provider", pa.string()),
            ("feed", pa.string()),
            ("instrument_type", pa.string()),
            ("instrument_key", pa.string()),
            ("symbol", pa.string()),
            ("ts_event", pa.timestamp("us", tz="UTC")),
            ("ts_ingest", pa.timestamp("us", tz="UTC")),
            ("ts_available", pa.timestamp("us", tz="UTC")),
            ("source", pa.string()),
            ("schema_version", pa.string()),
            ("quality_flags", pa.list_(pa.string())),
            ("short_date", pa.date32()),
            ("short_interest", pa.int64()),
            ("days_to_cover", pa.float64()),
            ("short_percent_float", pa.float64()),
            ("short_percent_outstanding", pa.float64()),
        ]
    ),
    "ftd": pa.schema(
        [
            ("event_id", pa.string()),
            ("provider", pa.string()),
            ("feed", pa.string()),
            ("instrument_type", pa.string()),
            ("instrument_key", pa.string()),
            ("symbol", pa.string()),
            ("ts_event", pa.timestamp("us", tz="UTC")),
            ("ts_ingest", pa.timestamp("us", tz="UTC")),
            ("ts_available", pa.timestamp("us", tz="UTC")),
            ("source", pa.string()),
            ("schema_version", pa.string()),
            ("quality_flags", pa.list_(pa.string())),
            ("ftd_date", pa.date32()),
            ("quantity", pa.int64()),
            ("price", pa.float64()),
            ("value", pa.float64()),
        ]
    ),
    "seasonality": pa.schema(
        [
            ("event_id", pa.string()),
            ("provider", pa.string()),
            ("feed", pa.string()),
            ("instrument_type", pa.string()),
            ("instrument_key", pa.string()),
            ("symbol", pa.string()),
            ("ts_event", pa.timestamp("us", tz="UTC")),
            ("ts_ingest", pa.timestamp("us", tz="UTC")),
            ("ts_available", pa.timestamp("us", tz="UTC")),
            ("source", pa.string()),
            ("schema_version", pa.string()),
            ("quality_flags", pa.list_(pa.string())),
            ("month", pa.int64()),
            ("avg_return", pa.float64()),
            ("median_return", pa.float64()),
            ("win_rate", pa.float64()),
            ("sample_years", pa.int64()),
        ]
    ),
    # Reference Data
    "option_contract": pa.schema(
        [
            ("event_id", pa.string()),
            ("provider", pa.string()),
            ("feed", pa.string()),
            ("instrument_type", pa.string()),
            ("instrument_key", pa.string()),
            ("symbol", pa.string()),
            ("ts_event", pa.timestamp("us", tz="UTC")),
            ("ts_ingest", pa.timestamp("us", tz="UTC")),
            ("ts_available", pa.timestamp("us", tz="UTC")),
            ("source", pa.string()),
            ("schema_version", pa.string()),
            ("quality_flags", pa.list_(pa.string())),
            ("underlying", pa.string()),
            ("occ_symbol", pa.string()),
            ("expiry", pa.date32()),
            ("strike", pa.float64()),
            ("put_call", pa.string()),
            ("bid", pa.float64()),
            ("ask", pa.float64()),
            ("last", pa.float64()),
            ("volume", pa.float64()),
            ("open_interest", pa.float64()),
            ("underlying_price", pa.float64()),
            # Greeks
            ("delta", pa.float64()),
            ("gamma", pa.float64()),
            ("theta", pa.float64()),
            ("vega", pa.float64()),
            ("rho", pa.float64()),
            ("iv", pa.float64()),
            # SCD fields
            ("multiplier", pa.int64()),
            ("style", pa.string()),
            ("exchange", pa.string()),
            ("valid_from", pa.timestamp("us", tz="UTC")),
            ("valid_to", pa.timestamp("us", tz="UTC")),
            ("revision_id", pa.string()),
        ]
    ),
    "news": pa.schema(
        [
            ("event_id", pa.string()),
            ("provider", pa.string()),
            ("feed", pa.string()),
            ("instrument_type", pa.string()),
            ("instrument_key", pa.string()),
            ("symbol", pa.string()),
            ("ts_event", pa.timestamp("us", tz="UTC")),
            ("ts_ingest", pa.timestamp("us", tz="UTC")),
            ("ts_available", pa.timestamp("us", tz="UTC")),
            ("source", pa.string()),
            ("schema_version", pa.string()),
            ("quality_flags", pa.list_(pa.string())),
            ("news_id", pa.string()),
            ("ts_published", pa.timestamp("us", tz="UTC")),
            ("ts_updated", pa.timestamp("us", tz="UTC")),
            ("headline", pa.string()),
            ("summary", pa.string()),
            ("body", pa.string()),
            ("url", pa.string()),
            ("source_name", pa.string()),
            ("author", pa.string()),
            ("symbols", pa.string()),  # JSON array of ticker symbols
            ("images", pa.string()),  # JSON array of image objects
            ("valid_from", pa.timestamp("us", tz="UTC")),
            ("valid_to", pa.timestamp("us", tz="UTC")),
            ("revision_id", pa.string()),
        ]
    ),
    "orderbook": pa.schema(
        [
            ("event_id", pa.string()),
            ("provider", pa.string()),
            ("feed", pa.string()),
            ("instrument_type", pa.string()),
            ("instrument_key", pa.string()),
            ("symbol", pa.string()),
            ("ts_event", pa.timestamp("us", tz="UTC")),
            ("ts_ingest", pa.timestamp("us", tz="UTC")),
            ("ts_available", pa.timestamp("us", tz="UTC")),
            ("source", pa.string()),
            ("schema_version", pa.string()),
            ("quality_flags", pa.list_(pa.string())),
            ("bids_json", pa.string()),  # JSON array of [price, size]
            ("asks_json", pa.string()),  # JSON array of [price, size]
            ("depth", pa.int64()),
        ]
    ),
    # V3: Alternative Data (Congress, Insider, Institution, Politician)
    "congress_trades": pa.schema(
        [
            ("event_id", pa.string()),
            ("provider", pa.string()),
            ("feed", pa.string()),
            ("instrument_type", pa.string()),
            ("instrument_key", pa.string()),
            ("symbol", pa.string()),
            ("ts_event", pa.timestamp("us", tz="UTC")),
            ("ts_ingest", pa.timestamp("us", tz="UTC")),
            ("ts_available", pa.timestamp("us", tz="UTC")),
            ("source", pa.string()),
            ("schema_version", pa.string()),
            ("quality_flags", pa.list_(pa.string())),
            ("trade_id", pa.string()),
            ("politician_name", pa.string()),
            ("politician_party", pa.string()),
            ("politician_state", pa.string()),
            ("politician_chamber", pa.string()),
            ("trade_type", pa.string()),
            ("trade_date", pa.date32()),
            ("disclosure_date", pa.date32()),
            ("amount_min", pa.float64()),
            ("amount_max", pa.float64()),
            ("asset_type", pa.string()),
            ("is_late", pa.bool_()),
            ("politician_id", pa.string()),
            ("owner", pa.string()),
            ("asset_description", pa.string()),
            ("cap_gains_over_200", pa.bool_()),
        ]
    ),
    "insider_trades": pa.schema(
        [
            ("event_id", pa.string()),
            ("provider", pa.string()),
            ("feed", pa.string()),
            ("instrument_type", pa.string()),
            ("instrument_key", pa.string()),
            ("symbol", pa.string()),
            ("ts_event", pa.timestamp("us", tz="UTC")),
            ("ts_ingest", pa.timestamp("us", tz="UTC")),
            ("ts_available", pa.timestamp("us", tz="UTC")),
            ("source", pa.string()),
            ("schema_version", pa.string()),
            ("quality_flags", pa.list_(pa.string())),
            ("filing_id", pa.string()),
            ("insider_name", pa.string()),
            ("insider_title", pa.string()),
            ("insider_relationship", pa.string()),
            ("trade_type", pa.string()),
            ("trade_date", pa.date32()),
            ("shares", pa.float64()),
            ("price", pa.float64()),
            ("value", pa.float64()),
            ("shares_owned_after", pa.float64()),
            ("filing_date", pa.date32()),
            # Additional fields
            ("stock_price", pa.float64()),
        ]
    ),
    "insider_flow": pa.schema(
        [
            ("event_id", pa.string()),
            ("provider", pa.string()),
            ("feed", pa.string()),
            ("instrument_type", pa.string()),
            ("instrument_key", pa.string()),
            ("symbol", pa.string()),
            ("ts_event", pa.timestamp("us", tz="UTC")),
            ("ts_ingest", pa.timestamp("us", tz="UTC")),
            ("ts_available", pa.timestamp("us", tz="UTC")),
            ("source", pa.string()),
            ("schema_version", pa.string()),
            ("quality_flags", pa.list_(pa.string())),
            ("period", pa.string()),
            ("period_start", pa.date32()),
            ("period_end", pa.date32()),
            ("sector", pa.string()),
            ("total_buys", pa.int64()),
            ("total_sells", pa.int64()),
            ("buy_value", pa.float64()),
            ("sell_value", pa.float64()),
            ("net_value", pa.float64()),
            ("top_buyers_json", pa.string()),
            ("top_sellers_json", pa.string()),
        ]
    ),
    "institution_holdings": pa.schema(
        [
            ("event_id", pa.string()),
            ("provider", pa.string()),
            ("feed", pa.string()),
            ("instrument_type", pa.string()),
            ("instrument_key", pa.string()),
            ("symbol", pa.string()),
            ("ts_event", pa.timestamp("us", tz="UTC")),
            ("ts_ingest", pa.timestamp("us", tz="UTC")),
            ("ts_available", pa.timestamp("us", tz="UTC")),
            ("source", pa.string()),
            ("schema_version", pa.string()),
            ("quality_flags", pa.list_(pa.string())),
            ("filing_id", pa.string()),
            ("institution_name", pa.string()),
            ("institution_cik", pa.string()),
            ("holding_symbol", pa.string()),
            ("shares", pa.float64()),
            ("value", pa.float64()),
            ("quarter_end", pa.date32()),
            ("change_shares", pa.float64()),
            ("change_pct", pa.float64()),
            ("portfolio_pct", pa.float64()),
            ("filing_date", pa.date32()),
        ]
    ),
    "institution_activity": pa.schema(
        [
            ("event_id", pa.string()),
            ("provider", pa.string()),
            ("feed", pa.string()),
            ("instrument_type", pa.string()),
            ("instrument_key", pa.string()),
            ("symbol", pa.string()),
            ("ts_event", pa.timestamp("us", tz="UTC")),
            ("ts_ingest", pa.timestamp("us", tz="UTC")),
            ("ts_available", pa.timestamp("us", tz="UTC")),
            ("source", pa.string()),
            ("schema_version", pa.string()),
            ("quality_flags", pa.list_(pa.string())),
            ("filing_id", pa.string()),
            ("institution_name", pa.string()),
            ("institution_cik", pa.string()),
            ("filing_date", pa.date32()),
            ("quarter_end", pa.date32()),
            ("total_value", pa.float64()),
            ("holdings_count", pa.int64()),
            ("new_positions", pa.int64()),
            ("closed_positions", pa.int64()),
            ("increased_positions", pa.int64()),
            ("decreased_positions", pa.int64()),
        ]
    ),
    "politician_trades": pa.schema(
        [
            ("event_id", pa.string()),
            ("provider", pa.string()),
            ("feed", pa.string()),
            ("instrument_type", pa.string()),
            ("instrument_key", pa.string()),
            ("symbol", pa.string()),
            ("ts_event", pa.timestamp("us", tz="UTC")),
            ("ts_ingest", pa.timestamp("us", tz="UTC")),
            ("ts_available", pa.timestamp("us", tz="UTC")),
            ("source", pa.string()),
            ("schema_version", pa.string()),
            ("quality_flags", pa.list_(pa.string())),
            ("trade_id", pa.string()),
            ("politician_id", pa.string()),
            ("politician_name", pa.string()),
            ("politician_party", pa.string()),
            ("trade_type", pa.string()),
            ("trade_date", pa.date32()),
            ("disclosure_date", pa.date32()),
            ("amount_min", pa.float64()),
            ("amount_max", pa.float64()),
            ("asset_description", pa.string()),
            ("comment", pa.string()),
        ]
    ),
    # V4: Market Analytics (Analyst, Fundamentals, Events, Indicators)
    "analyst_ratings": pa.schema(
        [
            ("event_id", pa.string()),
            ("provider", pa.string()),
            ("feed", pa.string()),
            ("instrument_type", pa.string()),
            ("instrument_key", pa.string()),
            ("symbol", pa.string()),
            ("ts_event", pa.timestamp("us", tz="UTC")),
            ("ts_ingest", pa.timestamp("us", tz="UTC")),
            ("ts_available", pa.timestamp("us", tz="UTC")),
            ("source", pa.string()),
            ("schema_version", pa.string()),
            ("quality_flags", pa.list_(pa.string())),
            ("rating_id", pa.string()),
            ("analyst_name", pa.string()),
            ("analyst_firm", pa.string()),
            ("rating", pa.string()),
            ("rating_prior", pa.string()),
            ("price_target", pa.float64()),
            ("price_target_prior", pa.float64()),
            ("rating_date", pa.date32()),
            ("action", pa.string()),
        ]
    ),
    "stock_fundamentals": pa.schema(
        [
            ("event_id", pa.string()),
            ("provider", pa.string()),
            ("feed", pa.string()),
            ("instrument_type", pa.string()),
            ("instrument_key", pa.string()),
            ("symbol", pa.string()),
            ("ts_event", pa.timestamp("us", tz="UTC")),
            ("ts_ingest", pa.timestamp("us", tz="UTC")),
            ("ts_available", pa.timestamp("us", tz="UTC")),
            ("source", pa.string()),
            ("schema_version", pa.string()),
            ("quality_flags", pa.list_(pa.string())),
            ("snapshot_date", pa.date32()),
            ("company_name", pa.string()),
            ("sector", pa.string()),
            ("industry", pa.string()),
            ("market_cap", pa.float64()),
            ("pe_ratio", pa.float64()),
            ("forward_pe", pa.float64()),
            ("peg_ratio", pa.float64()),
            ("pb_ratio", pa.float64()),
            ("ps_ratio", pa.float64()),
            ("eps", pa.float64()),
            ("eps_growth", pa.float64()),
            ("dividend_yield", pa.float64()),
            ("dividend_per_share", pa.float64()),
            ("revenue", pa.float64()),
            ("revenue_growth", pa.float64()),
            ("profit_margin", pa.float64()),
            ("operating_margin", pa.float64()),
            ("roe", pa.float64()),
            ("roa", pa.float64()),
            ("debt_to_equity", pa.float64()),
            ("current_ratio", pa.float64()),
            ("beta", pa.float64()),
            ("shares_outstanding", pa.float64()),
            ("float_shares", pa.float64()),
            ("avg_volume", pa.float64()),
            ("price", pa.float64()),
            ("high_52w", pa.float64()),
            ("low_52w", pa.float64()),
            ("exchange", pa.string()),
            ("country", pa.string()),
            ("description", pa.string()),
        ]
    ),
    "economic_events": pa.schema(
        [
            ("event_id", pa.string()),
            ("provider", pa.string()),
            ("feed", pa.string()),
            ("instrument_type", pa.string()),
            ("instrument_key", pa.string()),
            ("symbol", pa.string()),
            ("ts_event", pa.timestamp("us", tz="UTC")),
            ("ts_ingest", pa.timestamp("us", tz="UTC")),
            ("ts_available", pa.timestamp("us", tz="UTC")),
            ("source", pa.string()),
            ("schema_version", pa.string()),
            ("quality_flags", pa.list_(pa.string())),
            ("event_name", pa.string()),
            ("event_type", pa.string()),
            ("event_date", pa.date32()),
            ("event_time", pa.string()),
            ("country", pa.string()),
            ("importance", pa.string()),
            ("actual", pa.string()),
            ("forecast", pa.string()),
            ("previous", pa.string()),
            ("source_url", pa.string()),
        ]
    ),
    "market_indicators": pa.schema(
        [
            ("event_id", pa.string()),
            ("provider", pa.string()),
            ("feed", pa.string()),
            ("instrument_type", pa.string()),
            ("instrument_key", pa.string()),
            ("symbol", pa.string()),
            ("ts_event", pa.timestamp("us", tz="UTC")),
            ("ts_ingest", pa.timestamp("us", tz="UTC")),
            ("ts_available", pa.timestamp("us", tz="UTC")),
            ("source", pa.string()),
            ("schema_version", pa.string()),
            ("quality_flags", pa.list_(pa.string())),
            ("indicator_name", pa.string()),
            ("indicator_date", pa.date32()),
            ("indicator_time", pa.string()),
            ("value", pa.float64()),
            ("value_prior", pa.float64()),
            ("change", pa.float64()),
            ("change_pct", pa.float64()),
            ("percentile", pa.float64()),
            ("metadata_json", pa.string()),
        ]
    ),
    # V5: Options Deep Data
    "option_history": pa.schema(
        [
            ("event_id", pa.string()),
            ("provider", pa.string()),
            ("feed", pa.string()),
            ("instrument_type", pa.string()),
            ("instrument_key", pa.string()),
            ("symbol", pa.string()),
            ("ts_event", pa.timestamp("us", tz="UTC")),
            ("ts_ingest", pa.timestamp("us", tz="UTC")),
            ("ts_available", pa.timestamp("us", tz="UTC")),
            ("source", pa.string()),
            ("schema_version", pa.string()),
            ("quality_flags", pa.list_(pa.string())),
            ("occ_symbol", pa.string()),
            ("history_date", pa.date32()),
            ("open", pa.float64()),
            ("high", pa.float64()),
            ("low", pa.float64()),
            ("close", pa.float64()),
            ("volume", pa.float64()),
            ("open_interest", pa.float64()),
            ("implied_volatility", pa.float64()),
            ("delta", pa.float64()),
            ("gamma", pa.float64()),
            ("theta", pa.float64()),
            ("vega", pa.float64()),
        ]
    ),
    "option_trades": pa.schema(
        [
            ("event_id", pa.string()),
            ("provider", pa.string()),
            ("feed", pa.string()),
            ("instrument_type", pa.string()),
            ("instrument_key", pa.string()),
            ("symbol", pa.string()),
            ("ts_event", pa.timestamp("us", tz="UTC")),
            ("ts_ingest", pa.timestamp("us", tz="UTC")),
            ("ts_available", pa.timestamp("us", tz="UTC")),
            ("source", pa.string()),
            ("schema_version", pa.string()),
            ("quality_flags", pa.list_(pa.string())),
            # Option trades-specific
            ("underlying_symbol", pa.string()),
            ("option_symbol", pa.string()),
            ("strike", pa.float64()),
            ("expiry", pa.date32()),
            ("option_type", pa.string()),
            ("premium", pa.float64()),
            ("size", pa.float64()),
            ("price", pa.float64()),
            ("volume", pa.float64()),
            ("open_interest", pa.float64()),
            ("underlying_price", pa.float64()),
            # Greeks
            ("delta", pa.float64()),
            ("gamma", pa.float64()),
            ("theta", pa.float64()),
            ("vega", pa.float64()),
            ("rho", pa.float64()),
            ("implied_volatility", pa.float64()),
            # NBBO
            ("nbbo_ask", pa.float64()),
            ("nbbo_bid", pa.float64()),
            # Volume breakdowns
            ("ask_vol", pa.float64()),
            ("bid_vol", pa.float64()),
            ("mid_vol", pa.float64()),
            ("multi_vol", pa.float64()),
            ("stock_multi_vol", pa.float64()),
            ("no_side_vol", pa.float64()),
            # Metadata
            ("exchange", pa.string()),
            ("trade_id", pa.string()),
            ("canceled", pa.bool_()),
            ("er_time", pa.string()),
            ("next_earnings_date", pa.string()),
            ("sector", pa.string()),
            ("tags", pa.string()),  # JSON array of tags
        ]
    ),
    "option_chain_snapshot": pa.schema(
        [
            ("event_id", pa.string()),
            ("provider", pa.string()),
            ("feed", pa.string()),
            ("instrument_type", pa.string()),
            ("instrument_key", pa.string()),
            ("symbol", pa.string()),
            ("ts_event", pa.timestamp("us", tz="UTC")),
            ("ts_ingest", pa.timestamp("us", tz="UTC")),
            ("ts_available", pa.timestamp("us", tz="UTC")),
            ("source", pa.string()),
            ("schema_version", pa.string()),
            ("quality_flags", pa.list_(pa.string())),
            ("snapshot_ts", pa.timestamp("us", tz="UTC")),
            ("underlying", pa.string()),
            ("underlying_price", pa.float64()),
            ("expiry", pa.date32()),
            ("chain_json", pa.string()),
            ("total_call_volume", pa.float64()),
            ("total_put_volume", pa.float64()),
            ("total_call_oi", pa.float64()),
            ("total_put_oi", pa.float64()),
            ("atm_iv", pa.float64()),
            # Per-contract fields from NormalizedOptionContract
            ("occ_symbol", pa.string()),
            ("strike", pa.float64()),
            ("put_call", pa.string()),
            ("bid", pa.float64()),
            ("ask", pa.float64()),
            ("last", pa.float64()),
            ("volume", pa.float64()),
            ("open_interest", pa.float64()),
            # Greeks
            ("delta", pa.float64()),
            ("gamma", pa.float64()),
            ("theta", pa.float64()),
            ("vega", pa.float64()),
            ("rho", pa.float64()),
            ("iv", pa.float64()),
            # Size fields
            ("bid_size", pa.float64()),
            ("ask_size", pa.float64()),
            ("last_trade_size", pa.float64()),
        ]
    ),
    "volume_profile": pa.schema(
        [
            ("event_id", pa.string()),
            ("provider", pa.string()),
            ("feed", pa.string()),
            ("instrument_type", pa.string()),
            ("instrument_key", pa.string()),
            ("symbol", pa.string()),
            ("ts_event", pa.timestamp("us", tz="UTC")),
            ("ts_ingest", pa.timestamp("us", tz="UTC")),
            ("ts_available", pa.timestamp("us", tz="UTC")),
            ("source", pa.string()),
            ("schema_version", pa.string()),
            ("quality_flags", pa.list_(pa.string())),
            ("occ_symbol", pa.string()),
            ("profile_date", pa.date32()),
            ("price_level", pa.float64()),
            ("volume", pa.float64()),
            ("cumulative_volume", pa.float64()),
            ("pct_of_total", pa.float64()),
        ]
    ),
    "group_flow": pa.schema(
        [
            ("event_id", pa.string()),
            ("provider", pa.string()),
            ("feed", pa.string()),
            ("instrument_type", pa.string()),
            ("instrument_key", pa.string()),
            ("symbol", pa.string()),
            ("ts_event", pa.timestamp("us", tz="UTC")),
            ("ts_ingest", pa.timestamp("us", tz="UTC")),
            ("ts_available", pa.timestamp("us", tz="UTC")),
            ("source", pa.string()),
            ("schema_version", pa.string()),
            ("quality_flags", pa.list_(pa.string())),
            ("group_name", pa.string()),
            ("group_type", pa.string()),
            ("flow_date", pa.date32()),
            ("expiry", pa.date32()),
            ("call_gex", pa.float64()),
            ("put_gex", pa.float64()),
            ("net_gex", pa.float64()),
            ("call_dex", pa.float64()),
            ("put_dex", pa.float64()),
            ("net_premium", pa.float64()),
        ]
    ),
    # V6: ETF Deep Data
    "etf_metadata": pa.schema(
        [
            ("event_id", pa.string()),
            ("provider", pa.string()),
            ("feed", pa.string()),
            ("instrument_type", pa.string()),
            ("instrument_key", pa.string()),
            ("symbol", pa.string()),
            ("ts_event", pa.timestamp("us", tz="UTC")),
            ("ts_ingest", pa.timestamp("us", tz="UTC")),
            ("ts_available", pa.timestamp("us", tz="UTC")),
            ("source", pa.string()),
            ("schema_version", pa.string()),
            ("quality_flags", pa.list_(pa.string())),
            ("etf_symbol", pa.string()),
            ("snapshot_date", pa.date32()),
            ("fund_name", pa.string()),
            ("issuer", pa.string()),
            ("expense_ratio", pa.float64()),
            ("aum", pa.float64()),
            ("avg_volume", pa.float64()),
            ("inception_date", pa.date32()),
            ("asset_class", pa.string()),
            ("category", pa.string()),
            ("index_tracked", pa.string()),
            ("leverage_factor", pa.float64()),
        ]
    ),
    "etf_sector_weights": pa.schema(
        [
            ("event_id", pa.string()),
            ("provider", pa.string()),
            ("feed", pa.string()),
            ("instrument_type", pa.string()),
            ("instrument_key", pa.string()),
            ("symbol", pa.string()),
            ("ts_event", pa.timestamp("us", tz="UTC")),
            ("ts_ingest", pa.timestamp("us", tz="UTC")),
            ("ts_available", pa.timestamp("us", tz="UTC")),
            ("source", pa.string()),
            ("schema_version", pa.string()),
            ("quality_flags", pa.list_(pa.string())),
            ("etf_symbol", pa.string()),
            ("weight_date", pa.date32()),
            ("weight_type", pa.string()),
            ("weight_name", pa.string()),
            ("weight_pct", pa.float64()),
            ("change_pct", pa.float64()),
        ]
    ),
    "forex": pa.schema(
        [
            ("event_id", pa.string()),
            ("provider", pa.string()),
            ("feed", pa.string()),
            ("instrument_type", pa.string()),
            ("instrument_key", pa.string()),
            ("symbol", pa.string()),
            ("ts_event", pa.timestamp("us", tz="UTC")),
            ("ts_ingest", pa.timestamp("us", tz="UTC")),
            ("ts_available", pa.timestamp("us", tz="UTC")),
            ("source", pa.string()),
            ("schema_version", pa.string()),
            ("quality_flags", pa.list_(pa.string())),
            ("pair", pa.string()),
            ("bid", pa.float64()),
            ("ask", pa.float64()),
            ("mid", pa.float64()),
            ("open", pa.float64()),
            ("high", pa.float64()),
            ("low", pa.float64()),
            ("close", pa.float64()),
        ]
    ),
    "treasury_yields": pa.schema(
        [
            ("event_id", pa.string()),
            ("provider", pa.string()),
            ("feed", pa.string()),
            ("instrument_type", pa.string()),
            ("instrument_key", pa.string()),
            ("symbol", pa.string()),
            ("ts_event", pa.timestamp("us", tz="UTC")),
            ("ts_ingest", pa.timestamp("us", tz="UTC")),
            ("ts_available", pa.timestamp("us", tz="UTC")),
            ("source", pa.string()),
            ("schema_version", pa.string()),
            ("quality_flags", pa.list_(pa.string())),
            ("date", pa.string()),
            ("maturity", pa.string()),
            ("yield_pct", pa.float64()),
        ]
    ),
    # Real-time market status feeds
    "lulds": pa.schema(
        [
            ("event_id", pa.string()),
            ("provider", pa.string()),
            ("feed", pa.string()),
            ("instrument_type", pa.string()),
            ("instrument_key", pa.string()),
            ("symbol", pa.string()),
            ("ts_event", pa.timestamp("us", tz="UTC")),
            ("ts_ingest", pa.timestamp("us", tz="UTC")),
            ("ts_available", pa.timestamp("us", tz="UTC")),
            ("source", pa.string()),
            ("schema_version", pa.string()),
            ("quality_flags", pa.list_(pa.string())),
            ("timestamp", pa.timestamp("us", tz="UTC")),
            ("upper_limit", pa.float64()),
            ("lower_limit", pa.float64()),
            ("indicator", pa.string()),
        ]
    ),
    "statuses": pa.schema(
        [
            ("event_id", pa.string()),
            ("provider", pa.string()),
            ("feed", pa.string()),
            ("instrument_type", pa.string()),
            ("instrument_key", pa.string()),
            ("symbol", pa.string()),
            ("ts_event", pa.timestamp("us", tz="UTC")),
            ("ts_ingest", pa.timestamp("us", tz="UTC")),
            ("ts_available", pa.timestamp("us", tz="UTC")),
            ("source", pa.string()),
            ("schema_version", pa.string()),
            ("quality_flags", pa.list_(pa.string())),
            ("timestamp", pa.timestamp("us", tz="UTC")),
            ("status_code", pa.string()),
            ("status_message", pa.string()),
            ("reason_code", pa.string()),
            ("reason_message", pa.string()),
            ("tape", pa.string()),
        ]
    ),
    "corrections": pa.schema(
        [
            ("event_id", pa.string()),
            ("provider", pa.string()),
            ("feed", pa.string()),
            ("instrument_type", pa.string()),
            ("instrument_key", pa.string()),
            ("symbol", pa.string()),
            ("ts_event", pa.timestamp("us", tz="UTC")),
            ("ts_ingest", pa.timestamp("us", tz="UTC")),
            ("ts_available", pa.timestamp("us", tz="UTC")),
            ("source", pa.string()),
            ("schema_version", pa.string()),
            ("quality_flags", pa.list_(pa.string())),
            ("timestamp", pa.timestamp("us", tz="UTC")),
            ("exchange", pa.string()),
            ("original_trade_id", pa.string()),
            ("original_price", pa.float64()),
            ("original_size", pa.int64()),
            ("original_conditions", pa.string()),  # JSON-serialized list
            ("corrected_trade_id", pa.string()),
            ("corrected_price", pa.float64()),
            ("corrected_size", pa.int64()),
            ("corrected_conditions", pa.string()),  # JSON-serialized list
            ("tape", pa.string()),
        ]
    ),
    # Phase 3: Cerberus advanced strategy feeds
    "etf_tide": pa.schema(
        [
            ("event_id", pa.string()),
            ("provider", pa.string()),
            ("feed", pa.string()),
            ("instrument_type", pa.string()),
            ("instrument_key", pa.string()),
            ("symbol", pa.string()),
            ("ts_event", pa.timestamp("us", tz="UTC")),
            ("ts_ingest", pa.timestamp("us", tz="UTC")),
            ("ts_available", pa.timestamp("us", tz="UTC")),
            ("source", pa.string()),
            ("schema_version", pa.string()),
            ("quality_flags", pa.list_(pa.string())),
            # ETF tide-specific
            ("tide_type", pa.string()),
            ("ticker", pa.string()),
            ("tide_date", pa.string()),
            ("net_call_premium", pa.float64()),
            ("net_put_premium", pa.float64()),
            ("net_volume", pa.int64()),
            ("sentiment", pa.string()),
        ]
    ),
    "auctions": pa.schema(
        [
            ("event_id", pa.string()),
            ("provider", pa.string()),
            ("feed", pa.string()),
            ("instrument_type", pa.string()),
            ("instrument_key", pa.string()),
            ("symbol", pa.string()),
            ("ts_event", pa.timestamp("us", tz="UTC")),
            ("ts_ingest", pa.timestamp("us", tz="UTC")),
            ("ts_available", pa.timestamp("us", tz="UTC")),
            ("source", pa.string()),
            ("schema_version", pa.string()),
            ("quality_flags", pa.list_(pa.string())),
            # Auction-specific (Alpaca /stocks/auctions)
            ("auction_type", pa.string()),  # "open" or "close"
            ("auction_price", pa.float64()),
            ("imbalance_size", pa.int64()),
            ("imbalance_side", pa.string()),  # "buy", "sell", "none"
            ("paired_shares", pa.int64()),
            ("reference_price", pa.float64()),
        ]
    ),
}


# Default schema for unknown feeds
DEFAULT_SCHEMA = pa.schema(
    [
        ("event_id", pa.string()),
        ("provider", pa.string()),
        ("feed", pa.string()),
        ("instrument_type", pa.string()),
        ("instrument_key", pa.string()),
        ("symbol", pa.string()),
        ("ts_event", pa.timestamp("us", tz="UTC")),
        ("ts_ingest", pa.timestamp("us", tz="UTC")),
        ("ts_available", pa.timestamp("us", tz="UTC")),
        ("source", pa.string()),
        ("schema_version", pa.string()),
        ("quality_flags", pa.list_(pa.string())),
        ("payload_json", pa.string()),  # Store payload as JSON string
    ]
)


def get_silver_schema(feed: str) -> pa.Schema:
    """Get the canonical Silver schema for a feed."""
    return SILVER_SCHEMAS.get(feed, DEFAULT_SCHEMA)


__all__ = ["DEFAULT_SCHEMA", "SILVER_SCHEMAS", "get_silver_schema"]
