"""Ops module for Heber operational requirements.

Per PRD §12, this module provides reliability and observability utilities.
"""

from heber.ops.reliability import (
    BloomFilter,
    EventDeduplicator,
    DeadLetterQueue,
    DLQEvent,
    DeduplicationResult,
    retry_with_backoff,
    retry_with_backoff_async,
)
from heber.ops.logging import (
    configure_logging,
    get_logger,
    log_event_received,
    log_batch_written,
    log_error,
    log_dlq_event,
    log_retry,
)
from heber.ops.metrics import (
    start_metrics_server,
    set_service_info,
    record_event_received,
    record_event_processed,
    record_batch_processed,
    record_dedupe_drop,
    record_write,
    record_write_error,
    record_ingest_latency,
    record_compaction,
    record_api_request,
    record_dlq_event,
    set_consumer_lag,
    set_hotstore_lag,
)
from heber.ops.alerting import (
    AlertRule,
    Severity,
    ALERTING_RULES,
    DASHBOARDS,
    generate_prometheus_rules_yaml,
    get_alerting_rules,
    get_dashboard_specs,
)
from heber.ops.tracing import (
    configure_tracing,
    get_tracer,
    traced,
    extract_trace_context,
    inject_trace_context,
    get_current_trace_id,
    span_process_batch,
    span_dedupe_check,
    span_write_bronze,
    span_write_silver,
    span_api_request,
)
from heber.ops.health import (
    HealthStatus,
    ReadinessStatus,
    HealthCheck,
    LivenessResponse,
    ReadinessResponse,
    register_dependency_check,
    unregister_dependency_check,
    check_liveness,
    check_readiness,
    check_startup,
    mark_startup_complete,
    mark_startup_incomplete,
    is_startup_complete,
    create_redis_check,
    create_postgres_check,
    create_s3_check,
    create_http_check,
    create_health_router,
)
from heber.ops.circuit_breaker import (
    DependencyType,
    CircuitState,
    CircuitBreakerSettings,
    DependencyInfo,
    CircuitBreaker,
    CircuitOpenError,
    DEGRADATION_MATRIX,
    get_circuit_breaker,
    get_all_circuit_breakers,
    get_dependency_info,
    is_hard_dependency,
    is_soft_dependency,
    get_degraded_header,
    with_circuit_breaker,
)
from heber.ops.lifecycle import (
    LifecycleState,
    ShutdownConfig,
    LifecycleCallbacks,
    LifecycleManager,
    InFlightTracker,
    RebalanceConfig,
    ConsumerGroupRebalancer,
    CANARY_METRICS,
    evaluate_canary_health,
    mark_canary_healthy,
    mark_canary_unhealthy,
    create_lifecycle_middleware,
)

__all__ = [
    # Reliability (§12.1-12.4)
    "BloomFilter",
    "EventDeduplicator",
    "DeadLetterQueue",
    "DLQEvent",
    "DeduplicationResult",
    "retry_with_backoff",
    "retry_with_backoff_async",
    # Logging (§12.3, §12.5.5)
    "configure_logging",
    "get_logger",
    "log_event_received",
    "log_batch_written",
    "log_error",
    "log_dlq_event",
    "log_retry",
    # Metrics (§12.5.1-12.5.3)
    "start_metrics_server",
    "set_service_info",
    "record_event_received",
    "record_event_processed",
    "record_batch_processed",
    "record_dedupe_drop",
    "record_write",
    "record_write_error",
    "record_ingest_latency",
    "record_compaction",
    "record_api_request",
    "record_dlq_event",
    "set_consumer_lag",
    "set_hotstore_lag",
    # Alerting (§12.5.4)
    "AlertRule",
    "Severity",
    "ALERTING_RULES",
    "DASHBOARDS",
    "generate_prometheus_rules_yaml",
    "get_alerting_rules",
    "get_dashboard_specs",
    # Tracing (§12.5.6)
    "configure_tracing",
    "get_tracer",
    "traced",
    "extract_trace_context",
    "inject_trace_context",
    "get_current_trace_id",
    "span_process_batch",
    "span_dedupe_check",
    "span_write_bronze",
    "span_write_silver",
    "span_api_request",
    # Health Checks (§12.12)
    "HealthStatus",
    "ReadinessStatus",
    "HealthCheck",
    "LivenessResponse",
    "ReadinessResponse",
    "register_dependency_check",
    "unregister_dependency_check",
    "check_liveness",
    "check_readiness",
    "check_startup",
    "mark_startup_complete",
    "mark_startup_incomplete",
    "is_startup_complete",
    "create_redis_check",
    "create_postgres_check",
    "create_s3_check",
    "create_http_check",
    "create_health_router",
    # Circuit Breakers (§12.13)
    "DependencyType",
    "CircuitState",
    "CircuitBreakerSettings",
    "DependencyInfo",
    "CircuitBreaker",
    "CircuitOpenError",
    "DEGRADATION_MATRIX",
    "get_circuit_breaker",
    "get_all_circuit_breakers",
    "get_dependency_info",
    "is_hard_dependency",
    "is_soft_dependency",
    "get_degraded_header",
    "with_circuit_breaker",
    # Lifecycle (§12.14)
    "LifecycleState",
    "ShutdownConfig",
    "LifecycleCallbacks",
    "LifecycleManager",
    "InFlightTracker",
    "RebalanceConfig",
    "ConsumerGroupRebalancer",
    "CANARY_METRICS",
    "evaluate_canary_health",
    "mark_canary_healthy",
    "mark_canary_unhealthy",
    "create_lifecycle_middleware",
]
